### ISSUE TITLE
Loading onnx model gives error

### ISSUE THREAD

**Issue by bspckishore** [PUTvision/qgis-plugin-deepness#108]
Hi,
I have trained a model and exported to onnx in ultralytics hub. But when I am loading the same in deepness plugin in qgis gives error
:  TypeError: 'type' object cannot be interpreted as an integer
![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/138761855/0def1763-5313-421b-8e0e-1ffd1fff57cf)

**Comment by przemyslaw-aszkowski** [comment]
Hi,

Seems like some bug related to reading the model parameters. Do you mind sharing the model file (or some simplified version of it)? We would debug it then.

Cheers,
Przemek

**Comment by Amjath22** [comment]
Hi, I had the same issue when i trained a detection model in Yolov7. After some minor modifications i rectified it. if you like i can share the code for .pt to ONNX conversion.

**Comment by bspckishore** [comment]
Hi Przemek,
Please find below the model file in onnx format.
[model_- 18 september 2023 14_50.zip](https://github.com/PUTvision/qgis-plugin-deepness/files/12655874/model_-.18.september.2023.14_50.zip)

**Comment by bspckishore** [comment]
Hi Amjath,
Can you please share the code to bspckishore@gmail.com.

Thanks

**Comment by Amjath22** [comment]
Okay.

**Comment by przemyslaw-aszkowski** [comment]
Hi both, please let me later know if you managed to solve the issue or if should I investigate.

**Comment by bspckishore** [comment]
Hi Przemek,
The code shared by Amjath didnt solved my problem, can you please look into it. 

Thanks

**Comment by przemyslaw-aszkowski** [comment]
Hi @bspckishore,
I think your model is YOLO segmentation. Is that right? If so, it is not supported yet, but we already scheduled it for development, you can track details here: 
![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/81692276/172dde3f-3dc3-4d38-a7cb-1e71c37a42a6)

**Comment by przemyslaw-aszkowski** [comment]
Hi @bspckishore,
Please have a look here: https://github.com/PUTvision/qgis-plugin-deepness/issues/114
Is your model also YOLO segmentation?
