### ISSUE TITLE
Unsupported layer units

### ISSUE THREAD

**Issue by ruckc** [PUTvision/qgis-plugin-deepness#128]
I have some data with a CRS of EPSG:4326, and i'm getting the 
'Unsupported layer units' Exception from processing_utils.py.

**Comment by przemyslaw-aszkowski** [comment]
Hi,

Unfortunately, it is a known issue, not resolved yet. For the time being, you can use a workaround as described in https://github.com/PUTvision/qgis-plugin-deepness/discussions/109

Cheers
Przemek

**Comment by przemyslaw-aszkowski** [comment]
Hi
Should be resolved now with [version 0.6.5](https://github.com/PUTvision/qgis-plugin-deepness/releases/tag/0.6.5)
