### ISSUE TITLE
Vector/raster output layers in the group do not hide correctly

### ISSUE THREAD

**Issue by Saareem** [PUTvision/qgis-plugin-deepness#130]
![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/11333369/0ee36b62-1427-49b6-aea7-a642dbd54451)

My env: Windows 10, QGIS 3.32.1. I'm testing with the latest release, but I don't see this being fixed on the latest devel either.

It appears there's a bug in the plugin where the model output channels inside the layer group do not set their visibility correctly. This is true for at least the MapProcessorSegmentation and the MapProcessorRegression. I haven't tested other map processors. The layers show on the canvas even though the layer is not checked in the layer tree. The visibility changes only when the layer group is switched off and on. Then the visibility is once again correct. 

In essence, change in the output layer visibility only occurs after the whole group is switched off and then back on.

I first thought this is a bug in QGIS but I've made changes to my own fork where this problem doesn't occur. It seems it's related to how the plugin adds layers inside the `run` method of the task.

> One thing to be very careful about is never to create widgets or alter gui in a task. This is a strict Qt guideline – gui must never be altered outside of the main thread. So your progress dialog must operate on the main thread, connecting to the progress report signals from the task which operates in the background thread. This also applies to “print” statements — these aren’t safe to use from a background thread in QGIS and can cause random crashes. Use the thread safe QgsMessageLog.logMessage() approach instead. Actually you should forget print and always use QgsMessageLog.

[It seems changing gui and print statements inside the run method is not a good idea](https://www.opengis.ch/2018/06/22/threads-in-pyqgis3/) but I'm not certain if accessing `QgsProject.instance()` have the same culprits. However, as I implemented a `finished` method where I do the layer adding for the MapProcessorSegmentation, this bug resolves. The original reason for my change was not this minor annoyance but intermittent random crashes when I tried to add more groups and layers than just the vector layers inside the `run` method. When I looked into this issue of crashes, I found some error messages pointing to thread violations. So, I recommend at least trying to move adding layers to the `finished` method of the map processors, especially if adding more than one output layer or layer group.

**Comment by przemyslaw-aszkowski** [comment]
Hi,
we also encountered this issue on some PCs but didn't have time to track this issue. Thank you very much for the analysis and potential solution. We definitively want to fix it. I would be grateful if you would like to create a pull request. 
Thanks,
Przemek

**Comment by przemyslaw-aszkowski** [comment]
Fixed now in 0.6.0, thanks
