### ISSUE TITLE
'Buildings Segmentation' Error in Segmentation models

### ISSUE THREAD

**Issue by kuyhni** [PUTvision/qgis-plugin-deepness#166]
hello. I'm trying to use 'Buildings Segmentation' among the Deepness_Segmentation models, but I'm getting the following error repeatedly. What can I do to resolve this?

![QGIS_Deepness_Error_Image](https://github.com/PUTvision/qgis-plugin-deepness/assets/162545975/d69bc245-4ce9-4f7f-8d75-122cfa93e1ff)

**Comment by Kleebaue** [comment]
Hi, thank you for you Feedback. 

Your error looks like you have installed an old version of onnxruntime - try to update it running OSGeo4W Shell and install
python3 -m pip install -U onnruntime
