### ISSUE TITLE
Python packages required by the plugin could not be loaded due to the following error: 

### ISSUE THREAD

**Issue by plangenh** [PUTvision/qgis-plugin-deepness#167]
thanks a lot for the development of the plugin! I am looking forward to testing it out!
When trying to install the plugin either through the Plug -In manager or through the .zip file I am running into the following error: 

`Attempting to install required packages...

Running command: 
  $ /Applications/QGIS.app/Contents/MacOS/bin/python3 -m pip install -U --target=/Users/heljo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/python3.9opencv-python-headless>=4.5.5.64,=1.12.1,
Collecting opencv-python-headless=4.5.5.64
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-macosx_10_16_x86_64.whl (55.7 MB)
Collecting onnxruntime=1.12.1
  Using cached onnxruntime-1.17.0-cp39-cp39-macosx_11_0_universal2.whl (14.8 MB)
Collecting numpy>=1.17.0
  Using cached numpy-1.26.4-cp39-cp39-macosx_10_9_x86_64.whl (20.6 MB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting protobuf
  Using cached protobuf-5.26.1-cp37-abi3-macosx_10_9_universal2.whl (404 kB)
Collecting packaging
  Using cached packaging-24.0-py3-none-any.whl (53 kB)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting flatbuffers
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, humanfriendly, sympy, protobuf, packaging, numpy, flatbuffers, coloredlogs, opencv-python-headless, onnxruntime
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
splot 1.1.3 requires descartes, which is not installed.
sphinx 2.4.3 requires alabaster=0.7, which is not installed.
sphinx 2.4.3 requires babel!=2.0,>=1.3, which is not installed.
sphinx 2.4.3 requires docutils>=0.12, which is not installed.
sphinx 2.4.3 requires imagesize, which is not installed.
sphinx 2.4.3 requires snowballstemmer>=1.1, which is not installed.
sphinx 2.4.3 requires sphinxcontrib-applehelp, which is not installed.
sphinx 2.4.3 requires sphinxcontrib-devhelp, which is not installed.
sphinx 2.4.3 requires sphinxcontrib-htmlhelp, which is not installed.
sphinx 2.4.3 requires sphinxcontrib-jsmath, which is not installed.
sphinx 2.4.3 requires sphinxcontrib-qthelp, which is not installed.
sphinx 2.4.3 requires sphinxcontrib-serializinghtml, which is not installed.
pysal 2.5.0 requires spopt>=0.1.2, which is not installed.
pysal 2.5.0 requires access>=1.1.3, but you have access 1.1.1 which is incompatible.
pysal 2.5.0 requires esda>=2.4.1, but you have esda 2.3.1 which is incompatible.
pysal 2.5.0 requires mapclassify>=2.4.3, but you have mapclassify 2.3.0 which is incompatible.
pysal 2.5.0 requires mgwr>=2.1.2, but you have mgwr 2.1.1 which is incompatible.
pysal 2.5.0 requires segregation>=2.0.0, but you have segregation 1.3.0 which is incompatible.
pysal 2.5.0 requires spaghetti>=1.6.2, but you have spaghetti 1.5.0 which is incompatible.
pysal 2.5.0 requires spglm>=1.0.8, but you have spglm 1.0.7 which is incompatible.
pysal 2.5.0 requires spint>=1.0.7, but you have spint 1.0.6 which is incompatible.
pysal 2.5.0 requires splot>=1.1.4, but you have splot 1.1.3 which is incompatible.
pysal 2.5.0 requires spreg>=1.2.4, but you have spreg 1.1.2.post1 which is incompatible.
pysal 2.5.0 requires tobler>=0.8.2, but you have tobler 0.3.1 which is incompatible.
pysal 2.5.0 requires urllib3>=1.26, but you have urllib3 1.24.3 which is incompatible.
Successfully installed coloredlogs-15.0.1 flatbuffers-24.3.25 humanfriendly-10.0 mpmath-1.3.0 numpy-1.26.4 onnxruntime-1.17.0 opencv-python-headless-4.9.0.80 packaging-24.0 protobuf-5.26.1 sympy-1.12

Packages installed correctly!

Installation of required packages finished. Validating installation...
Python packages required by the plugin could not be loaded due to the following error: 
Traceback (most recent call last):
  File "/Users/heljo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/dialogs/packages_installer/packages_installer_dialog.py", line 300, in _check_packages_installation_and_log
    import_packages()
  File "/Users/heljo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/dialogs/packages_installer/packages_installer_dialog.py", line 325, in import_packages
    import_package(package)
  File "/Users/heljo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/deepness/dialogs/packages_installer/packages_installer_dialog.py", line 320, in import_package
    importlib.import_module(package.import_name)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 986, in _find_and_load_unlocked
  File "", line 680, in _load_unlocked
  File "", line 855, in exec_module
  File "", line 228, in _call_with_frames_removed
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/__init__.py", line 5, in 
    from .cv2 import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libprotobuf.22.dylib
  Referenced from: /Applications/QGIS.app/Contents/Resources/python/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so
  Reason: tried: '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS.app/Contents/Frameworks/libprotobuf.22.dylib' (no such file), '/Applications/QGIS.app/Contents/MacOS/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS.app/Contents/Resources/grass78/lib/libprotobuf.22.dylib' (no such file), '/usr/local/lib/libprotobuf.22.dylib' (no such file), '/usr/lib/libprotobuf.22.dylib' (no such file, not in dyld cache)

Please try installing the packages again.`

**Comment by przemyslaw-aszkowski** [comment]
Hi,
looks like the installation of the packages succeded, but their verification afterwards failed. Please try to install the Python packages manually from the QGIS Python console.
Cheers
Przemek
