### ISSUE TITLE
Deepness Segmentor file roading error

### ISSUE THREAD

**Issue by JeongbaeJeon** [PUTvision/qgis-plugin-deepness#170]
hello.

First of all, thank you so much for creating the deepness plugin for qgis.

I am studying the field of detecting objects using drone images. We are using YOLOv5 and YOLOv8 for object detection.
The .pt file learned in YOLO is converted to an onnx file, and Deepness's Detect model is performed perfectly without error.
However, when converting a .pt file learned using the Segmentation model to an onnx file and using Deepness' Segmentor model, the following error occurs.

![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/138568107/5270cb52-b2ea-40e2-a0e8-6c73f4bc72ed)

I don't understand what this error means, is there any solution?

**Comment by bartoszptak** [comment]
Could you share any information about your model, the repository you used to train, and the command you used to export? If it possible, you can share to me your onnx model as well, I'll check what is wrong.

**Comment by GeoLuisAmarilla** [comment]
Hello,
I have the same problem, I used Ultralytics to train and export the model with the YOLOv8l-SEG architecture
link to model: https://hub.ultralytics.com/models/RKCFCsGnktxMMevHlTSi

**Comment by GeoLuisAmarilla** [comment]
> Could you share any information about your model, the repository you used to train, and the command you used to export? If it possible, you can share to me your onnx model as well, I'll check what is wrong.

Hello,
I have the same problem, I used Ultralytics to train and export the model with the YOLOv8l-SEG architecture
link to model: https://hub.ultralytics.com/models/RKCFCsGnktxMMevHlTSi

**Comment by JeongbaeJeon** [comment]
I cloned ultralytics' code and studied it with Yolo8s-seg.pt.

python code: yolo segment train model=yolov8s-seg.pt data='./data.yaml' epochs=200 imgsz=1024

The best.pt file saved through this was converted to an onnx file using the code shown in the picture below.

![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/138568107/7731db8c-af0d-4603-b749-24b9e8b2584f)

I will provide you with a link to share the created file.

https://drive.google.com/drive/folders/1Bvbil8xRWTeE4HI7ZC3C7gYObcHSflr0?usp=drive_link

**Comment by bartoszptak** [comment]
@JeongbaeJeon 
> I will provide you with a link to share the created file.
> 
> https://drive.google.com/drive/folders/1Bvbil8xRWTeE4HI7ZC3C7gYObcHSflr0?usp=drive_link

I've loaded your model and inferred without any issues. Are you sure, that the correct model type and YOLO type were selected?

![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/20326060/4579a720-9216-4ab2-92bf-9af6daaf7b8a)

**Comment by bartoszptak** [comment]
@GeoLuisAmarilla 
> Hello, I have the same problem, I used Ultralytics to train and export the model with the YOLOv8l-SEG architecture link to model: https://hub.ultralytics.com/models/RKCFCsGnktxMMevHlTSi

It is highly unpleasant that you provide the link to a model that is behind a barrier and the Ultralytics account is required. We will not help you until you provide the model in onnx.

**Comment by Martin-Dawson** [comment]
I have the same issue with an ONNX export from Ultralytics.  The model used was a Yolov8m segmentation and displays acceptable results in the Ultralytics preview. A link to the model file is here: https://1drv.ms/u/s!Aq_JPactK6wGjKVSwNr9JLkS8SsLPQ?e=ey9mdD

**Comment by bartoszptak** [comment]
@Martin-Dawson your model works totally fine for me. Do you use YOLO_ultralytics_segmentarion or Segmentowe model? There is huge difference between instance segmentation and semantic segmentation tasks.

**Comment by Martin-Dawson** [comment]
Bartosz,
I believe I used YOLO_ultralytics_segmentation.  The problem I have is on trying to load the model: [cid:3452b34b-e333-4c15-a2a5-2e2e736ca812]



Best regards,

Martin Dawson

07572 345 486

________________________________

**Comment by JeongbaeJeon** [comment]
The onnx file I built loads without error in Deepness's Detector model. However, when I load the file in Segmentor model, I get an error.
You can run it by selecting YOLO_Ultralytics_segmentation as the type of detection parameters in the detector model.
However, I would like to try the Segmentor model. I wonder why this happens.

![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/138568107/aec8ae77-fb44-40c5-8cea-9fa7c3d82543)

**Comment by GeoLuisAmarilla** [comment]
> @GeoLuisAmarilla
> 
> > Hello, I have the same problem, I used Ultralytics to train and export the model with the YOLOv8l-SEG architecture link to model: https://hub.ultralytics.com/models/RKCFCsGnktxMMevHlTSi
> 
> It is highly unpleasant that you provide the link to a model that is behind a barrier and the Ultralytics account is required. We will not help you until you provide the model in onnx.

I'm so sorry!!!. I thought it would be open to download without login.
I put it on a drive: 
https://drive.google.com/file/d/1O6VE06OwszRJunljo6tOab8D1raqynov/view?usp=sharing

**Comment by przemyslaw-aszkowski** [comment]
@JeongbaeJeon The YOLO_Ultralytics_segmentation model needs to be used as Detector. The Segmentor models are only for models with the following output: [BATCH_SIZE, 1, SIZE_PX, SIZE_PX].

@GeoLuisAmarilla Thanks for the file, your model works! You just need to select the proper detector class, as there are many different YOLO models. See the configuration on my screenshot: 
![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/81692276/6122be9d-e5fb-4dd8-8f1e-1775323b8f24)

@Martin-Dawson I believe it is the same case as above, see the configuration on my screenshot (especially the configuration in red boxes).

Let me know if there are any other issues, and please share the results of your models once you are happy with them!

Cheers
Przemek

**Comment by GeoLuisAmarilla** [comment]
> @JeongbaeJeon The YOLO_Ultralytics_segmentation model needs to be used as Detector. The Segmentor models are only for models with the following output: [BATCH_SIZE, 1, SIZE_PX, SIZE_PX].
> 
> @GeoLuisAmarilla Thanks for the file, your model works! You just need to select the proper detector class, as there are many different YOLO models. See the configuration on my screenshot: ![image](https://private-user-images.githubusercontent.com/81692276/328292650-6122be9d-e5fb-4dd8-8f1e-1775323b8f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTU3NzMsIm5iZiI6MTcxNjQ5NTQ3MywicGF0aCI6Ii84MTY5MjI3Ni8zMjgyOTI2NTAtNjEyMmJlOWQtZTVmYi00ZGQ4LThmMWUtMTc3NTMyM2I4ZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDIwMTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNzM1NDc3ZGIyMDJiYmUyZTZhZjdkM2RiOGUxN2I0OTY5ZDY5NjVkZDhhOTRlM2YxZWI5NWEyZWNjZDA3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dh3s-GtfNfZqX85YunwHYFgVCMsBjU8-UBdyLzLGZk8)
> 
> @Martin-Dawson I believe it is the same case as above, see the configuration on my screenshot (especially the configuration in red boxes).
> 
> Let me know if there are any other issues, and please share the results of your models once you are happy with them!
> 
> Cheers Przemek

Hello.
Yes it works without any errors! but in the detection option it only draws the detected boundaries and does not perform the segmentation. It looks like this:
![Screenshot 2024-05-23 110525](https://github.com/PUTvision/qgis-plugin-deepness/assets/168565607/98207493-0c52-4815-bff8-4eb33b3f8b63)

**Comment by bartoszptak** [comment]
> Hello. Yes it works without any errors! but in the detection option it only draws the detected boundaries and does not perform the segmentation. It looks like this: ![Screenshot 2024-05-23 110525](https://private-user-images.githubusercontent.com/168565607/333329043-98207493-0c52-4815-bff8-4eb33b3f8b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTk3NjEsIm5iZiI6MTcxNjQ5OTQ2MSwicGF0aCI6Ii8xNjg1NjU2MDcvMzMzMzI5MDQzLTk4MjA3NDkzLTBjNTItNDgxNS1iZmY4LTRlYjMzYjNmOGI2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMTI0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWM5NmM4NTk3Mjk3MmVmMDdkNmYwOTNhNDQ2YTJkNzMwZTI1MWRhYTQ0OGNkYTZjMjExYmE0ZDhlM2FhMGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42KmmuSuzsgKDgxal9eLAnD9bew5RViPJDqRWjbOhfs)

Could you share a screenshot of your Deepness config you set before inference? Could you share informations about operating system, qgis version, deepness version. Could you shortly describe how you prepare your model (I'm mostly asking about dataset labels etc).
