### ISSUE TITLE
DLL load failed while importing _core error help...

### ISSUE THREAD

**Issue by ni-um-ma** [PUTvision/qgis-plugin-deepness#178]
The deepness plugin test file cannot be executed.

When I try to run test_map_processor_segmentation_landcover_example.py, the following error occurs.

`D:\qgis-plugin-deepness-devel\qgis_deepness\.venv\Scripts\python.exe D:\qgis-plugin-deepness-devel\qgis_deepness\test_map_processor_segmentation_landcover_example.py 
Traceback (most recent call last):
  File "D:\qgis-plugin-deepness-devel\qgis_deepness\test_map_processor_segmentation_landcover_example.py", line 22, in <module>
    from test_utils import create_default_input_channels_mapping_for_rgb_bands, create_rlayer_from_file, init_qgis
  File "D:\qgis-plugin-deepness-devel\qgis-plugin-deepness-devel\test\test_utils.py", line 4, in <module>
    from qgis.core import (QgsApplication, QgsCoordinateReferenceSystem, QgsProject, QgsRasterLayer, QgsRectangle,
  File "C:\Program Files\QGIS 3.34.8\apps\qgis-ltr\python\qgis\core\__init__.py", line 25, in <module>
    from qgis._core import *
ImportError: DLL load failed while importing _core: 지정된 모듈을 찾을 수 없습니다.`

Environment:
Operating System: Windows
QGIS Version: 3.34.8
Python Environment: Virtual Environment in PyCharm
Python version : 3.8.1

The QGIS installation path: C:\Program Files\QGIS 3.34.8
The script I am trying to run: D:\qgis-plugin-deepness-devel\qgis_deepness\test_map_processor_segmentation_landcover_example.py
The test_utils.py file is located at: D:\qgis-plugin-deepness-devel\qgis-plugin-deepness-devel\test\test_utils.py

Added the necessary QGIS directories to the PATH, PYTHONPATH, and QT_PLUGIN_PATH environment variables both in the script and in PyCharm's Run/Debug Configurations.
Verified the presence of qgis._core.pyd in the C:\Program Files\QGIS 3.34.8\apps\qgis-ltr\python\qgis\core directory.

Despite correctly setting up the environment variables, I am facing a persistent ImportError: DLL load failed while importing _core error. The _core.pyd file exists in the expected directory, and the environment variables appear to be set correctly.

I would appreciate any guidance or suggestions to resolve this issue.

**Comment by przemyslaw-aszkowski** [comment]
Hi

We never tried running the development environment on Windows - we used only Linux. If you have such an option, please try to run it there.

Though there seem to be some solutions online, maybe it will help: https://stackoverflow.com/questions/75483158/from-qgis-core-import-importerror-dll-load-failed-while-importing-core-t

Cheers
Przemek
