### ISSUE TITLE
Unsupported Layer Unit 

### ISSUE THREAD

**Issue by fauzan9585** [PUTvision/qgis-plugin-deepness#179]
Hello,

There is a pop up message that I received after I click the "run" button (See below)
<img width="437" alt="Python Error" src="https://github.com/user-attachments/assets/633f7fd3-a4ac-4d51-a648-d0d97128027c">

Please see the parameter that I set below 
<img width="278" alt="deepness UI 1" src="https://github.com/user-attachments/assets/03040976-ed41-4107-bf02-b0c321d3c581">
<img width="256" alt="deepness UI 2" src="https://github.com/user-attachments/assets/6456adba-cd94-4be3-a7ce-5017e1a9323a">
<img width="276" alt="deepness UI 3" src="https://github.com/user-attachments/assets/8f4db54c-7cdf-4826-94d7-aa373265ea2e">

Do you have any ideas to solve this issue? 
For your information, My dataset was trained using Yolov5

**Comment by przemyslaw-aszkowski** [comment]
Hi, 
it is an issue with your orthophoto. Please see discussion here:
https://github.com/PUTvision/qgis-plugin-deepness/discussions/109
Cheers 
Przemek
