### ISSUE TITLE
Error with Aerial Cars Detection model after upgrade to Deepness 0.6.4

### ISSUE THREAD

**Issue by hewag1975** [PUTvision/qgis-plugin-deepness#189]
Hi, 
thank you for the great plugin. 

**Describe the bug**
I recently updated to version 0.6.4 and since then the car detection using the [Aerial Cars Detection model](https://chmura.put.poznan.pl/s/vgOeUN4H4tGsrGm) throws the following error:

![image](https://github.com/user-attachments/assets/baff8f4d-22e3-4d92-a08d-7e9ca0178548)

**To Reproduce**
Open QGIS and Deepness Plugin, add an image to analyze
Select Input Layer and processed area
Select Model Type "Detector"
Load the model onxx-file

**Expected behavior**
No error, model should be loaded to do inference

**Screenshots (including Deepness options selected)**
![image](https://github.com/user-attachments/assets/1c9ee7ed-a8e0-4c2f-9e40-7203f285b424)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC
 - QGiS: 3.34-4
 - Deepness version: 0.6.4

Thanks for your help.

**Comment by bartoszptak** [comment]
Hi @hewag1975 , could you perform these activities:
1. Run QGIS
2. Open Python Console (Ctrl+Alt+P)
3. Type `import onnxruntime, sys`
4. Type `sys.version`
5. Type `onnxruntime.__version__`
6. Type `onnxruntime.get_build_info()`
7. Type `onnxruntime.get_available_providers()`
8. Attach the screenshot with the versions.

It would be helpful for me to debug that issue.

PS: You can try to update the onnxruntime library version—the instruction you can find [here](https://github.com/PUTvision/qgis-plugin-deepness/discussions/187#discussioncomment-10889417). Just search the words "update the ONNXRuntime library in QGIS:".

**Comment by hewag1975** [comment]
Hi @bartoszptak, 

here is the output:
```
import onnxruntime, sys
sys.version
'3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)]'
onnxruntime.__version__
'1.17.0'
onnxruntime.get_build_info()
'ORT Build Info: git-branch=HEAD, git-commit-id=5f0b62cde5, build type=RelWithDebInfo, cmake cxx flags: /guard:cf /DWIN32 /D_WINDOWS /DWINAPI_FAMILY=100 /DWINVER=0x0A00 /D_WIN32_WINNT=0x0A00 /DNTDDI_VERSION=0x0A000000 /O2 /Ob1 /DNDEBUG /EHsc /EHsc /wd26812 -DEIGEN_HAS_C99_MATH -DCPUINFO_SUPPORTED'
onnxruntime.get_available_providers()
['AzureExecutionProvider', 'CPUExecutionProvider']
```
Updating the ONNXRuntime as you suggested resolves the problem
```
onnxruntime.__version__
'1.19.2'
```
Thanks. Feel free to close.
