### ISSUE TITLE
Error from OpenCV code

### ISSUE THREAD

**Issue by geo-antony** [PUTvision/qgis-plugin-deepness#81]
Hi, 
I am using the Landcover model. Everytime i run a trial with vector file (Area mask layer) more than ~ 400 sq.km on satellite imagery, i get this error. I have tried this with Google, Bing, ESRI. The error invariably crops up. could you please suggest a resolution for this?

Error! Processing error: "Unhandled exception occurred. See Python Console for details"!

Details: error - Unknown C++ exception from OpenCV code
Last Traceback: 
  File "C:\Users/STPA CTP(RE)TVM/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deepness\processing\map_processor\map_processor_segmentation.py", line 55, in _run
    full_result_img = cv2.medianBlur(full_result_img, blur_size)

**Comment by przemyslaw-aszkowski** [comment]
Hi @geo-antony ,
with a 400 km^2 image the processing module ends up with 2500000000 pixels to process. As it is allocated in the memory as an array, it is probably too much for the underlying library.

I would recommend processing the data in smaller chunks (e.g. 200 km^2) and merging the resulting output layers afterwards in QGIS.
And thanks for reporting, we will add a memory check on Windows and show a readable error message.

**Comment by geo-antony** [comment]
Thank you @przemyslaw-aszkowski for the recommendation.
Yes, in fact area below 300 sq.km seems to work just fine. 

May I add a suggestion:
- if you could provide the option to run a batch process, it'd be very helpful.

Thank you once again for this wonderful plugin.

**Comment by przemyslaw-aszkowski** [comment]
Hi, nice to hear your feedback :) 
Batch processing sounds like a good idea, we will definitively consider adding it
